### ISSUE TITLE
LiberationMono-Bold.ttf on RHEL7 causes glyphy to abort

### ISSUE THREAD

**Issue by rconde01** [behdad/glyphy#31]
The abort occurs in process_contour. Interestingly, the version here:

https://www.fontsquirrel.com/fonts/liberation-mono

works ok. I didn't investigate the lineage.

**Comment by behdad** [comment]
I'm not maintaining GLyphy really.  What are you using it for?

**Comment by rconde01** [comment]
A commercial product...but it's working great for us. I didn't necessarily expect a fix per se...more an FYI. Is there some alternative you recommend? I don't know of anything else.

**Comment by behdad** [comment]
Interesting!  I'll take a look.  Can you attach the font here?

**Comment by rconde01** [comment]
[LiberationMono-Bold-RHEL7.zip](https://github.com/behdad/glyphy/files/2542657/LiberationMono-Bold-RHEL7.zip)
Here you go!!

In the meantime I just removed the aborts which are not really good for us anyhow. I think maybe there's a small artifact on the upper case A but I didn't look too deeply. It was definitely specific strings which were triggering it.

**Comment by behdad** [comment]
Thanks.  I just disabled them.

**Comment by behdad** [comment]
The 'A' artifact doesn't seem related.

**Comment by behdad** [comment]
Humm.  Or maybe it is.  That hits the second abort that I disabled.  I'll try fixing it properly.

**Comment by behdad** [comment]
The font has two points very close to each other there..  I might fix some time.

**Comment by behdad** [comment]
Fixed the actual bug.

**Comment by rconde01** [comment]
cool!
