### ISSUE TITLE
porting shaders to OpenGL 3.2 (first working version! yay )

### ISSUE THREAD

**Issue by mgood7123** [behdad/glyphy#36]
i am trying to port glyphy to OpenGL 3 (OpenGL 3.2 context) with `#version 330 core` and `#version 320 es` and i currently get no text rendered

it seems like the default GL context glew creates is `2.1 INTEL-14.7.8` (`2.1`) tho this might vary 

these are my current changes https://github.com/mgood7123/glyphy-opengl3/commit/0104d65f225afa993ef0af3ea3ff135661fe3dc0

**Comment by mgood7123** [comment]
i got GL 3 to work, it now renders everything that OpenGL 2 could :)

https://github.com/mgood7123/glyphy-opengl3/commit/81e8412d9cb6bd9326c130f33b86efb7e941cb38

tho i had to rewrite part of the OPENGL block in demo-common.h to include GL3 headers, only tested on APPLE no not sure if headers will work on linux/windows/android yet

**Comment by behdad** [comment]
Thanks! Let me test this on my Linux.

**Comment by behdad** [comment]
Can you send a pull request?

**Comment by behdad** [comment]
> [mgood7123/glyphy-opengl3@81e8412](https://github.com/mgood7123/glyphy-opengl3/commit/81e8412d9cb6bd9326c130f33b86efb7e941cb38)

Your `GL_CHECK_ERROR` changes are too noisy. Please use a macro like my existing `gl` to just prefix all sites that need checking so they look like:
```
  GL_CHECK glUseProgram (...);
```

**Comment by mgood7123** [comment]
yea, if you like, here is one ported to QT https://github.com/mgood7123/glyphy-QT

**Comment by mgood7123** [comment]
> Can you send a pull request?


> > [mgood7123/glyphy-opengl3@81e8412](https://github.com/mgood7123/glyphy-opengl3/commit/81e8412d9cb6bd9326c130f33b86efb7e941cb38)
> 
> Your `GL_CHECK_ERROR` changes are too noisy. Please use a macro like my existing `gl` to just prefix all sites that need checking so they look like:
> 
> ```
>   GL_CHECK glUseProgram (...);
> ```

fixed in https://github.com/behdad/glyphy/pull/38
