### ISSUE TITLE
Demo: Windows Visual Studio “hb.h”: No such file or directory

### ISSUE THREAD

**Issue by moyy** [behdad/glyphy#51]
I build in windows visual studio and vcpkg

but compile error: “hb.h”: No such file or directory

I also install harfbuzz yet

Please help that What I can do

**Comment by behdad** [comment]
You need to make GLyphy see your installed HarfBuzz somehow.

**Comment by SnosMe** [comment]
Just need to add "harfbuzz" folder in these includes.

![image](https://user-images.githubusercontent.com/4292308/188421477-540a5d0b-6673-47ef-8ac8-0c4563352584.png)
